runtime: nodejs20
instance_class: F2

entrypoint: npm run start

# Umgebungsvariablen mit Secret Manager-Referenzen
env_variables:
  DATABASE_CLIENT: "postgres"
  NODE_ENV: "production"

# Secrets aus dem Secret Manager
# Diese werden zur Laufzeit automatisch als Umgebungsvariablen verfügbar gemacht
beta_settings:
  cloud_sql_instances: "strapi-website-454221:europe-west3:DEINE-SQL-INSTANZ"  # Falls du Cloud SQL verwendest

# Automatische Skalierung
automatic_scaling:
  min_instances: 1
  max_instances: 3
  target_cpu_utilization: 0.65