# app.yaml
# Definiert die Laufzeitumgebung.
runtime: nodejs20

# Gibt an, welche Instanzgröße verwendet werden soll.
instance_class: F2

# Der Befehl, der ausgeführt wird, um deine Anwendung im Produktionsmodus zu starten.
entrypoint: npm run start

