# cloudbuild.yaml
steps:
  - name: "gcr.io/cloud-builders/gcloud"
    args: [
      "app",
      "deploy",
      "--quiet",
      # Setzt den Datenbank-Client auf 'postgres', um den SQLite-Fehler zu beheben
      "--update-env-vars=DATABASE_CLIENT=postgres",

      # Übergibt die Secrets sicher als Umgebungsvariablen.
      # Der Wert $DATABASE_URL wird vom Secret Manager bezogen (durch secretEnv)
      # und direkt an App Engine weitergegeben.
      "--update-env-vars=DATABASE_URL=$$DATABASE_URL,CLOUDINARY_NAME=$$CLOUDINARY_NAME,CLOUDINARY_KEY=$$CLOUDINARY_KEY,CLOUDINARY_SECRET=$$CLOUDINARY_SECRET"
    ]
    # Alle Secrets, die Sie in den gcloud-Befehl injizieren wollen,
    # müssen hier aufgeführt werden.
    secretEnv: ['DATABASE_URL', 'CLOUDINARY_NAME', 'CLOUDINARY_KEY', 'CLOUDINARY_SECRET']

options:
  logging: CLOUD_LOGGING_ONLY

# Konfiguration, die Cloud Build mitteilt, welche Secrets verwendet werden dürfen
availableSecrets:
  secretManager:
    - versionName: projects/strapi-website-454221/secrets/DATABASE_URL/versions/latest
      env: DATABASE_URL
    - versionName: projects/strapi-website-454221/secrets/CLOUDINARY_NAME/versions/latest
      env: CLOUDINARY_NAME
    - versionName: projects/strapi-website-454221/secrets/CLOUDINARY_KEY/versions/latest
      env: CLOUDINARY_KEY
    - versionName: projects/strapi-website-454221/secrets/CLOUDINARY_SECRET/versions/latest
      env: CLOUDINARY_SECRET