# cloudbuild.yaml
# Stellt sicher, dass alle Secrets an die App Engine Umgebung 端bergeben werden.
steps:
  - name: "gcr.io/cloud-builders/gcloud"
    # Die Argumente werden als eine Liste von Strings 端bergeben.
    args: [
      "app",
      "deploy",
      "--quiet",
      # Injiziert alle Umgebungsvariablen als einen einzigen String (ohne Zeilenumbruch)
      "--set-env-vars=DATABASE_CLIENT=postgres,DATABASE_URL=$$DATABASE_URL,CLOUDINARY_CLOUD_NAME=$$CLOUDINARY_CLOUD_NAME,CLOUDINARY_API_KEY=$$CLOUDINARY_API_KEY,CLOUDINARY_API_SECRET=$$CLOUDINARY_API_SECRET,ADMIN_JWT_SECRET=$$ADMIN_JWT_SECRET,API_TOKEN_SALT=$$API_TOKEN_SALT,APP_KEYS=$$APP_KEYS,JWT_SECRET=$$JWT_SECRET,TRANSFER_TOKEN_SALT=$$TRANSFER_TOKEN_SALT"  ]

    # Secrets, die vom Build-Schritt zur Laufzeit verwendet werden m端ssen
    secretEnv: [
      'DATABASE_URL',
      'CLOUDINARY_CLOUD_NAME',
      'CLOUDINARY_API_KEY',
      'CLOUDINARY_API_SECRET',
      'ADMIN_JWT_SECRET',
      'API_TOKEN_SALT',
      'APP_KEYS',
      'JWT_SECRET',
      'TRANSFER_TOKEN_SALT'
    ]

options:
  logging: CLOUD_LOGGING_ONLY

# Definition der Secret-Quellen (Muss mit der Projekt-ID 端bereinstimmen)
availableSecrets:
  secretManager:
    - versionName: projects/strapi-website-454221/secrets/DATABASE_URL/versions/latest
      env: DATABASE_URL
    - versionName: projects/strapi-website-454221/secrets/CLOUDINARY_CLOUD_NAME/versions/latest
      env: CLOUDINARY_CLOUD_NAME
    - versionName: projects/strapi-website-454221/secrets/CLOUDINARY_API_KEY/versions/latest
      env: CLOUDINARY_API_KEY
    - versionName: projects/strapi-website-454221/secrets/CLOUDINARY_API_SECRET/versions/latest
      env: CLOUDINARY_API_SECRET
    - versionName: projects/strapi-website-454221/secrets/ADMIN_JWT_SECRET/versions/latest
      env: ADMIN_JWT_SECRET
    - versionName: projects/strapi-website-454221/secrets/API_TOKEN_SALT/versions/latest
      env: API_TOKEN_SALT
    - versionName: projects/strapi-website-454221/secrets/APP_KEYS/versions/latest
      env: APP_KEYS
    - versionName: projects/strapi-website-454221/secrets/JWT_SECRET/versions/latest
      env: JWT_SECRET
    - versionName: projects/strapi-website-454221/secrets/TRANSFER_TOKEN_SALT/versions/latest
      env: TRANSFER_TOKEN_SALT