steps:
  # Schritt 1: Baue das Docker-Image
  # Wir verwenden den Standard-Docker-Builder von Google.
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        # Das Image wird mit der Region, Projekt-ID und dem Service-Namen getaggt.
        # Diese Variablen werden von Cloud Run automatisch bereitgestellt.
        'europe-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/$SERVICE_NAME:$COMMIT_SHA',
        '.',
      ]

# Hier weisen wir das gebaute Image Cloud Run zu.
images:
  - 'europe-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/$SERVICE_NAME:$COMMIT_SHA'

# WICHTIG: Hier fordern wir eine stärkere Maschine für den Build an.
# E2_HIGHCPU_8 hat 8 CPUs und deutlich mehr RAM als der Standard.
options:
  machineType: 'E2_HIGHCPU_8'
