steps:
  # Schritt 1: Build Docker Image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/strapi:$SHORT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/strapi:latest'
      - '.'

  # Schritt 2: Push Image zu Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/strapi:$SHORT_SHA'

  # Schritt 3: Deploy zu Cloud Run mit Secrets
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'strapi-app'
      - '--image=gcr.io/$PROJECT_ID/strapi:$SHORT_SHA'
      - '--region=europe-west3'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--memory=2Gi'
      - '--cpu=2'
      - '--min-instances=1'
      - '--max-instances=3'
      - '--set-env-vars=DATABASE_CLIENT=postgres,NODE_ENV=production'
      - '--set-secrets=DATABASE_URL=DATABASE_URL:latest,CLOUDINARY_CLOUD_NAME=CLOUDINARY_CLOUD_NAME:latest,CLOUDINARY_API_KEY=CLOUDINARY_API_KEY:latest,CLOUDINARY_API_SECRET=CLOUDINARY_API_SECRET:latest,ADMIN_JWT_SECRET=ADMIN_JWT_SECRET:latest,API_TOKEN_SALT=API_TOKEN_SALT:latest,APP_KEYS=APP_KEYS:latest,JWT_SECRET=JWT_SECRET:latest,TRANSFER_TOKEN_SALT=TRANSFER_TOKEN_SALT:latest'

images:
  - 'gcr.io/$PROJECT_ID/strapi:$SHORT_SHA'
  - 'gcr.io/$PROJECT_ID/strapi:latest'

options:
  logging: CLOUD_LOGGING_ONLY

timeout: 1600s